import csv

input_csv = 'csv/clean_movies_2018_2025.csv'
output_csv = 'csv/movies_with_code.csv'

country_map = {
    'Algeria': 'dz',
    'Angola': 'ao',
    'Benin': 'bj',
    'Botswana': 'bw',
    'Burkina Faso': 'bf',
    'Burundi': 'bi',
    'Cameroon': 'cm',
    'Central African Republic': 'cf',
    'Chad': 'td',
    'Comoros': 'km',
    'Congo Brazzaville': 'cg',
    'Congo Kinshasa': 'cd',
    'Cote d''Ivoire': 'ci',
    'Djibouti': 'dj',
    'Egypt': 'eg',
    'Equatorial Guinea': 'gq',
    'Eritrea': 'er',
    'Ethiopia': 'et',
    'Gabon': 'ga',
    'Gambia': 'gm',
    'Ghana': 'gh',
    'Guinea': 'gn',
    'Guinea-Bissau': 'gw',
    'Kenya': 'ke',
    'Lesotho': 'ls',
    'Liberia': 'lr',
    'Libya': 'ly',
    'Madagascar': 'mg',
    'Malawi': 'mw',
    'Mali': 'ml',
    'Mauritania': 'mr',
    'Mauritius': 'mu',
    'Morocco': 'ma',
    'Mozambique': 'mz',
    'Namibia': 'na',
    'Niger': 'ne',
    'Nigeria': 'ng',
    'Rwanda': 'rw',
    'Senegal': 'sn',
    'Seychelles': 'sc',
    'Sierra Leone': 'sl',
    'Somalia': 'so',
    'South Africa': 'za',
    'South Sudan': 'ss',
    'Sudan': 'sd',
    'Swaziland': 'sz',
    'Tanzania': 'tz',
    'Togo': 'tg',
    'Tunisia': 'tn',
    'Uganda': 'ug',
    'Zambia': 'zm',
    'Zimbabwe': 'zw',
    'Argentina': 'ar',
    'Bahamas': 'bs',
    'Barbados': 'bb',
    'Belize': 'bz',
    'Bermuda': 'bm',
    'Bolivia': 'bo',
    'Brazil': 'br',
    'Canada': 'ca',
    'Chile': 'cl',
    'Colombia': 'co',
    'Costa Rica': 'cr',
    'Cuba': 'cu',
    'Dominica': 'dm',
    'Dominican Republic': 'do',
    'Ecuador': 'ec',
    'El Salvador': 'sv',
    'Grenada': 'gd',
    'Guatemala': 'gt',
    'Guyana': 'gy',
    'Haiti': 'ht',
    'Honduras': 'hn',
    'Jamaica': 'jm',
    'Mexico': 'mx',
    'Nicaragua': 'ni',
    'Panama': 'pa',
    'Paraguay': 'py',
    'Peru': 'pe',
    'Puerto Rico': 'pr',
    'Suriname': 'sr',
    'Trinidad and Tobago': 'tt',
    'United States': 'us',
    'Uruguay': 'uy',
    'Venezuela': 've',
    'Afghanistan': 'af',
    'Armenia': 'am',
    'Azerbaijan': 'az',
    'Bahrain': 'bh',
    'Bangladesh': 'bd',
    'Bhutan': 'bt',
    'Brunei': 'bn',
    'Cambodia': 'kh',
    'China': 'cn',
    'Georgia': 'ge',
    'Hong Kong': 'hk',
    'India': 'in',
    'Indonesia': 'id',
    'Iran': 'ir',
    'Iraq': 'iq',
    'Israel': 'il',
    'Japan': 'jp',
    'Jordan': 'jo',
    'Kazakhstan': 'kz',
    'Kuwait': 'kw',
    'Kyrgyzstan': 'kg',
    'Laos': 'la',
    'Lebanon': 'lb',
    'Malaysia': 'my',
    'Maldives': 'mv',
    'Mongolia': 'mn',
    'Myanmar': 'mm',
    'Nepal': 'np',
    'North Korea': 'kp',
    'Oman': 'om',
    'Pakistan': 'pk',
    'Philippines': 'ph',
    'Qatar': 'qa',
    'Saudi Arabia': 'sa',
    'Singapore': 'sg',
    'South Korea': 'kr',
    'Sri Lanka': 'lk',
    'Syria': 'sy',
    'Taiwan': 'tw',
    'Tajikistan': 'tj',
    'Thailand': 'th',
    'Timor-Leste': 'tl',
    'Turkey': 'tr',
    'Turkmenistan': 'tm',
    'United Arab Emirates': 'ae',
    'Uzbekistan': 'uz',
    'Vietnam': 'vn',
    'Yemen': 'ye',
    'Albania': 'al',
    'Austria': 'at',
    'Belarus': 'by',
    'Belgium': 'be',
    'Bosnia and Herzegovina': 'ba',
    'Bulgaria': 'bg',
    'Croatia': 'hr',
    'Cyprus': 'cy',
    'Czech Republic': 'cz',
    'Denmark': 'dk',
    'Estonia': 'ee',
    'Finland': 'fi',
    'France': 'fr',
    'Germany': 'de',
    'Greece': 'gr',
    'Hungary': 'hu',
    'Iceland': 'is',
    'Ireland': 'ie',
    'Italy': 'it',
    'Latvia': 'lv',
    'Lithuania': 'lt',
    'Luxembourg': 'lu',
    'Macedonia': 'mk',
    'Malta': 'mt',
    'Moldova': 'md',
    'Montenegro': 'me',
    'Netherlands': 'nl',
    'Norway': 'no',
    'Poland': 'pl',
    'Portugal': 'pt',
    'Romania': 'ro',
    'Russia': 'ru',
    'Serbia': 'rs',
    'Slovakia': 'sk',
    'Slovenia': 'si',
    'Spain': 'sp',
    'Sweden': 'se',
    'Switzerland': 'ch',
    'Ukraine': 'ua',
    'United Kingdom': 'gb',
    'Australia': 'au',
    'Cook Islands': 'ck',
    'Fiji': 'fj',
    'Micronesia': 'fm',
    'New Zealand': 'nz',
    'Papua New Guinea': 'pg',
    'Samoa': 'ws',
    'Solomon Islands': 'sb',
    'Tokelau': 'tk',
    'Tonga': 'to',
    'Tuvalu': 'tv',
    'Vanuatu': 'vu',
    'United States of America': 'us',

}

with open(input_csv, 'r', encoding='utf-8') as infile:
    reader = csv.DictReader(infile)
    rows = list(reader)

for row in rows:
    country_name = row['country']
    row['country_code'] = country_map.get(country_name, 'XX').lower()

fieldnames = reader.fieldnames + ['country_code']
with open(output_csv, 'w', newline='', encoding='utf-8') as outfile:
    writer = csv.DictWriter(outfile, fieldnames=fieldnames)
    writer.writeheader()
    writer.writerows(rows)

print(f"New CSV generated with country_code: {output_csv}")
